name: Build and Deploy
on:
  push:
    branches:
      - master

env:
  VUE_APP_API_KEY: ${{secrets.VUE_APP_API_KEY}}
  VUE_APP_WEATHER_API: ${{secrets.VUE_APP_WEATHER_API}}
  VUE_APP_GEO_API: ${{secrets.VUE_APP_GEO_API}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and build
        run: |
          npm ci --no-fund --no-optional
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: release
          folder: dist
